services:
  api:
    build:
      dockerfile: Dockerfile.MultiStage
      context: .
      target: production
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    env_file:
      - .env.prod
    command: npm run start
    ports:
      - 3000:3000
#    depends_on:
#      - postgres
#    networks:
#      - app
#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - '5432:5432'
#    volumes:
#      - docker-nest-postgres:/var/lib/postgresql/data
#    networks:
#      - app
#
#networks:
#  app:
#    driver: bridge
#
#volumes:
#  docker-nest-postgres:
